version: "3"
# docker run -d --name firerpa --privileged -v ~/firerpa:/user -e DOMAIN=firerpa.local -e WEB_PORT=8000 -e API_PORT=65000 -p 8000:8000 -p 65000:65000 --restart always registry.device-farm.com/firerpa/server:latest
services:
        firerpa:
                container_name: hub
                image: .
                privileged: true
                volumes:
                        - ~/hub:/user
                        - ~/config.conf:/opt/easytier/config/default.conf
                environment:
                        - DOMAIN=firerpa.local
                        - WEB_PORT=8000
                        - API_PORT=65000
                        - ADDR=192.168.1.2
                ports:
                        - 8000:8000
                        - 65000:65000
                restart: always