name: Build and Push to GHCR
on:
  push:
    branches: [ main ]   # 仅 main 分支触发
    tags: [ v* ]         # 支持版本标签触发（如 v1.0.0）

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # 矩阵策略并行构建两种架构
    permissions:
      contents: read
      packages: write   # 授权写入 GHCR [1,4](@ref)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0 # 获取所有历史记录，迁移历史大文件时可能需要

      - name: Restore Git LFS cache
        uses: actions/cache@v3
        with:
          path: .git/lfs
          key: ${{ runner.os }}-git-lfs-${{ hashFiles('.gitattributes') }}
          restore-keys: |
            ${{ runner.os }}-git-lfs-

      # --- 核心配置 ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all  # 启用全平台模拟支持[1,7](@ref)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # 启用高效构建驱动[6](@ref)

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}   # 自动使用触发者账号
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub令牌认证[1,4](@ref)

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}  # 动态注入矩阵架构
          context: .
          push: true
          # 动态生成标签：ARM架构添加 "-arm" 后缀
          tags: |
            ghcr.io/${{ github.repository_owner }}/rpahub:${{ github.sha }}${{ matrix.platform == 'linux/arm64' && '-arm' || '' }}
            ghcr.io/${{ github.repository_owner }}/rpahub:latest${{ matrix.platform == 'linux/arm64' && '-arm' || '' }}
          #cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rpahub:buildcache  # 使用Registry缓存加速[6](@ref)
          #cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/rpahub:buildcache,mode=max

      # --- 可选：创建多架构Manifest（合并标签）---
  create-manifest:
    needs: build-push
    runs-on: ubuntu-latest
    permissions: { packages: write }
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # 使用同一令牌
      - name: Create Multi-Arch Manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/rpahub:latest \
            ghcr.io/${{ github.repository_owner }}/rpahub:latest \
            ghcr.io/${{ github.repository_owner }}/rpahub:latest-arm
