name: Build and Push to GHCR
on:
  push:
    branches: [ main ]   # 仅 main 分支触发
    tags: [ v* ]         # 支持版本标签触发（如 v1.0.0）
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # 必须授权写入 GHCR [1,3](@ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
     # --- 核心配置开始 ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/amd64,linux/arm64

      - name: Verify Builder
        run: docker buildx ls
      # --- 核心配置结束 ---
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}   # 自动使用触发者账号
          password: ${{ secrets.GITHUB_TOKEN }}   # 使用 GitHub 自动生成的令牌 [1,3,7](@ref)

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64 
          context: .   # Dockerfile 所在目录
          push: true   # 启用推送
          tags: |
            ghcr.io/${{ github.repository_owner }}/rpahub:latest
            ghcr.io/${{ github.repository_owner }}/rpahub:${{ github.sha }}
          cache-from: type=gha   # 启用缓存加速
          cache-to: type=gha,mode=max
